-- phpMyAdmin SQL Dump
-- version 4.8.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 01, 2018 at 11:07 AM
-- Server version: 10.1.32-MariaDB
-- PHP Version: 7.2.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bookstore`
--

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE `books` (
  `id` int(10) UNSIGNED NOT NULL,
  `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `author` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cover` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `saleprice` int(11) NOT NULL,
  `purchase_price` int(11) NOT NULL,
  `state` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`id`, `title`, `author`, `category`, `cover`, `description`, `saleprice`, `purchase_price`, `state`, `created_at`, `updated_at`) VALUES
(1, 'Sách Tranh Gợi Mở Nhận Biết: Toán Học 123', 'Gia Bảo - Đoàn Loan', 'Toán học', '1541059837_386828908.PNG', 'Quyển sách Sách Tranh Gợi Mở Nhận Biết: Toán Học 123 được biên soạn giúp các bé có thể nhận biết các chữ số từ 1 đến 200 cùng một số phép tính đơn giản.\r\n\r\nNội dung sách được trình bày rõ ràng, dễ hiểu với những hình ảnh minh họa sinh động đầy màu sắc, khuyến khích trẻ quan sát, tò mò, suy nghĩ, khám phá thế giới xung quanh.\r\n\r\nSách sẽ mang đến cho các em những hướng dẫn cùng hình ảnh minh họa trực quan về các chữ số và các phép tính cơ bản như: cộng, trừ, nhân, chia. Các phép so sánh sẽ giúp các em phân biệt to - nhỏ, cao - thấp, lớn - bé... tạo nền tảng cho bé học Toán sau này.\r\n\r\nĐồng thời, cách trình bày song ngữ Anh - Việt của quyển sách giúp trẻ làm quen với tiếng Anh, phát triển khả năng tư duy và ngôn ngữ.\r\n\r\nSách dành cho bé trong lứa tuổi bắt đầu nhận thức thế giới xung quanh, thông qua các hình ảnh về các sự vật xung quanh. Quyển sách sẽ góp phần giúp các bé phát triển tư duy nhận thức, nâng cao trí tuệ toàn diện, khả năng tưởng tượng và sáng tạo.', 19000, 16000, 1, '2018-11-01 08:10:37', '2018-11-01 08:10:37'),
(3, 'Bộ Sách Học Toán Qua Truyện Cổ Tích (Trọn Bộ 3 Cuốn)', 'Trần Thị Phương Thảo', 'Toán học', '1541060177_2131697986.PNG', 'Bộ Sách Học Toán Qua Truyện Cổ Tích (Trọn Bộ 3 Cuốn) là bộ sách sẽ giúp các bé có thể nâng cao khả năng học toán qua các câu chuyện cổ tích này.\r\n\r\nNgày xửa ngày xưa, ngay từ khi dấu chân loài người mới in trên mặt đất, truyện cổ tích đã ra đời. Những câu chuyện trong lời kể của cha, lời ru của mẹ đã thấm dần vào tâm hồn con trẻ. Theo năm tháng, đạo lý làm người, cách ăn ở của cha ông được gìn giữ và truyền lại dịu êm trong thế giới cổ tích kỳ diệu.\r\n\r\nĐến ngày nay, nhiều thế kỷ đã trôi qua, những lâu đài ngạo nghễ khi xưa đang âm thầm dõi theo những thành phố hiện đại nhấp nhô một biển nhà chọc trời. Những chiếc máy bay khổng lồ tung bay trên bầu trời đầy nắng giống như loài rồng huyền thoại đã tung bay hàng nghìn năm trước.\r\n\r\nVà các em bé không chỉ mơ về những công chúa hoàng tử, hay mơ về thế giới người tí hon lạ lùng hay những chiến công đội đá vá trời, hay kho báu giữa biển khơi mà còn muốn bay xa vào vũ trụ và nhìn sâu hơn vào thế giới siêu tí hon của vi khuẩn và các loài tảo. Nếu chỉ có triết lý làm người sẽ không đủ để các em bé vụt lớn thành những người khổng lồ mới. Các em cần tri thức toán học và khoa học để vững vàng trong thế giới hiện đại. Và thế là câu chuyện được viết lại thêm những bài toán để mạch suối nguồn của toán học được chảy trong thế giới cổ tích kỳ diệu. Toán học cũng sẽ đi vào lời kể của cha, lời ru của mẹ mỗi buổi trưa hè oi ả hay một buổi tối êm đềm trong cơn mưa mùa thu mát mẻ, khi giấc ngủ dịu dàng kéo đến, trong tiếng sột soạt của cơn gió khẽ lật những trang sách “Học Toán qua Truyện Cổ tích”.\r\n\r\nBộ gồm 3 cuốn:\r\n\r\nCây tre trăm đốt\r\nCây khế\r\nCóc kiện trời', 108000, 101000, 1, '2018-11-01 08:16:17', '2018-11-01 08:16:17'),
(4, 'Sách Vải Sabe Rubik Toán Học', 'Sách Vải Sabe', 'Toán học', '1541060399_854921801.PNG', 'Sách Vải Sabe Rubik Toán Học nhiều bạn nhỏ GHÉT toán học vì toán học khô khan nhưng học toán với các bạn nhỏ đâu phải chỉ là những phép tính. Học Toán còn vô số thứ thú vị hơn nhiều như:\r\nPhân biệt các hình dạng (hình tròn, hình vuông…)\r\nXòe tay ra chúng mình cùng đếm từ 1-10\r\nPhân biệt to nhỏ, biết so sánh nhiều hơn, ít hơn…\r\nXếp hình phát triển tư duy logic.\r\nHọc những thứ thú vị như thế, lại còn qua một bộ sách vải vô cùng đáng yêu thì chắc chắn sẽ khiến các bạn nhỏ cảm thấy Toán học là thứ gì đó rất gần gũi, quen thuộc trong cuộc sống chứ không chỉ là những con số khô khan và “đáng ghét”.\r\nHọc Toán theo cách này đảm bảo bố mẹ nào cũng nhận ra là bé có khả năng tư duy và trí thông minh Toán học', 155000, 147000, 1, '2018-11-01 08:19:59', '2018-11-01 08:19:59'),
(5, 'Khéo Tay Tinh Mắt - Sách Bóc Dán Thông Minh - Bước Đầu Học Toán', 'Liangzi Cartoon', 'Toán học', '1541060538_45263988.PNG', 'Khéo Tay Tinh Mắt - Sách Bóc Dán Thông Minh - Bước Đầu Học Toán\r\n\r\nBố mẹ hãy để bé trả lời những câu hỏi nho nhỏ trong từng trang sách, và tự tìm ra hình dán thích hợp, như vậy bé sẽ hiểu sâu, nhớ lâu, tinh mắt, khéo tay. Bố mẹ hãy hướng dẫn bé dán hình vào từng trang sách trước, rồi để bé bóc ra dán lên tủ, lên giường của mình, bé nào cũng sẽ thích mê! Những câu chuyện nhỏ thú vị kèm hình bóc dán đáng yêu là món quà đẹp tặng cho bé!\r\n\r\nBộ sách này gồm 4 cuốn: Rau quả thức ăn, Phương tiện giao thông, Loài vật ngộ nghĩnh và Bước đầu học toán.', 21000, 18500, 1, '2018-11-01 08:22:18', '2018-11-01 08:22:18'),
(6, 'Tủ Sách Bé Vào Lớp 1 - Bé Vui Học Toán (Dành Cho Trẻ Mẫu Giáo 4 - 5 Tuổi)', 'Lê Tuệ Minh - Lê Thu Ngọc', 'Toán học', '1541060681_1227584540.PNG', 'Tủ Sách Bé Vào Lớp 1 - Bé Vui Học Toán (Dành Cho Trẻ  Mẫu Giáo 4 - 5 Tuổi)\r\n\r\nMột trong những yêu cầu quan trọng để giúp trẻ học tốt chương trình lớp 1 là sự chuẩn bị đầy đủ các điều kiện về thể chất, trí tuệ, tình cảm, ngôn ngữ và một số kỹ năng cần thiết. Vì vậy, trẻ cần được dạy cách phát âm và làm quen với chữ cái, các mẫu chữ hoa - thường... Tủ Sách Bé Vào Lớp 1 là bộ sách hữu ích trong việc xây dựng nền tảng kiến thức, kĩ năng cho các em. Sách có nội dung phong phú với nhiều bài tập đa dạng theo hình thức trò chơi, phù hợp với các em trong độ tuổi 5 - 6 tuổi.\r\n\r\nMỗi tập nhấn mạnh vào một kỹ năng cơ bản: tô màu, tô chữ, tập phát âm, nối chữ và hình, tô nét cơ bản... Ngoài ra, sách còn kèm theo hình vẽ minh họa màu sinh động, giúp các em hứng thú hơn trong học tập.\r\n\r\nTủ Sách Bé Vào Lớp 1 - Bé Vui Học Toán (Dành Cho Trẻ  Mẫu Giáo 4 - 5 Tuổi) gồm các dạng bài tập rèn luyện lý thú, hữu ích.', 6000, 4500, 1, '2018-11-01 08:24:41', '2018-11-01 08:24:41'),
(7, 'Bộ Sách Thiên Tài Nhí - Cấp Độ 1: Toán Học', 'Jacques Thomas - Bilstein', 'Toán học', '1541061796_158688750.gif', 'Phát hành Toàn quốc bao gồm các hiểu biết về toán học cùng với các hoạt động sẽ giúp các bạn nhỏ hiểu rõ hơn về Thế giới và môi trường của các bạn nhỏ đang sinh sống.\r\n\r\nỞ cấp độ 1, các bạn nhỏ sẽ vừa được giải trí vừa được làm quen với các kỹ năng làm toán đầu tiên. Được học các số đếm đến 20. Đồng thời làm quen với các phép tính cộng, trừ đơn giản.\r\n\r\nCuốn sách này sẽ là món quà ý nghĩa cho các bậc phụ huynh và bé trong giai đoạn bé đang ở độ tuổi bắt đầu tiếp cận đến các con số và phép tính đơn giản.\r\n\r\nVừa học vừa chơi luôn sẽ tạo được hứng khởi cho các bé.', 38500, 37000, 1, '2018-11-01 08:43:16', '2018-11-01 08:43:16'),
(8, 'Sách Toán Singapore lớp 1 - Class 1B', 'Abel Chong', 'Toán học', '1541061987_1258532661.PNG', 'Bộ sách được xây dưng 3 phần với 3 bộ khác nhau gồm More than a textbook Maths Textbook & Workbook Primary P1A, P1B, P2A, P2B, P3A, P3B và phần bài tập củng cố cho mỗi bộ. Mỗi bộ phù hợp với 1 lứa tuổi theo thứ thự lớp 1,2, 3. More than a Textbook Maths Textbook & Workbook Primary không chỉ đơn giản là cuốn sách giáo khoa Singapore mà nó còn là một người bạn đồng hành cùng con yêu, cung cấp cho con những kỹ năng cơ bản nhất để tỏ tình thành công với toán học hiện đại. Với kết cấu rỗ ràng từng phần, bộ sách mang đến cho trẻ những kỹ năng tối quan trọng để chinh phục thành công môn toán đó là: Kỹ năng nhận dạng toán học: Tăng khả năng tư duy dạy trẻ biết cách nhận biết những dạng toán hay gặp, những mẫu toán chung và cách thức giải quyết những dạng toán theo công thức. Kỹ năng phân tích từng phần và tổng thể: Mỗi bài toán mẫu trong More than a textbook Maths Textbook & Workbook Primary đều được phân tích rõ ràng các bước. Mỗi phần của cuốn sarch đều được hướng dẫn cụ thể để có thể giúp trẻ giải quyết cả bài toán.', 150000, 139000, 1, '2018-11-01 08:46:27', '2018-11-01 08:46:27'),
(9, 'Giải Sách ViOlympic Toán 3 (Tập 1)', 'Nguyễn Đức Tấn, Nguyễn Đoàn Vũ, Nguyễn Anh Hoàng', 'Toán học', '1541062047_532143123.gif', 'Cuộc thi giải toán Violympic trên Internet là một cuộc thi đang rất phổ biến. Nó giúp các em phát triển tư duy và sử dụng công nghệ thông tin trong học tập. Sử dụng tốt cuốn sách này, các em sẽ nắm được cách giải các dạng toán, hoàn thành tốt các vòng thi Violympic.\r\n\r\nSách được dùng nhằm bồi dưỡng học sinh giỏi, là tài liệu tham khảo dành cho giáo viên và phụ huynh.', 72900, 70000, 1, '2018-11-01 08:47:27', '2018-11-01 08:47:27'),
(10, 'Sách Toán Lớp 4 (Song Ngữ Việt - Anh)', 'Nhiều Tác Giả', 'Toán học', '1541062117_1700521223.gif', 'Nhà xuất bản Giáo Dục Việt Nam đã có công văn số: 1114/NXBGDVN ngày 18 tháng 07 năm 2014 V/v phát hành bộ sách giáo khoa Toán song ngữ Việt – Anh năm học 2014 – 2015. Bộ sách nhằm mục đích hỗ trợ phát triển kỹ năng giao tiếp và khả năng sử dụng tiếng Anh như một công cụ để học toán.\r\n\r\nNội dung bộ sách được biên soạn, biên dịch theo đúng cấu trúc, nội dung và chương trình của sách giáo khoa đang được NXBGDVN xuất bản, phát hành hiện nay và sẽ giúp các em từng bước làm quen với việc học toán bằng tiếng Anh: từ việc biết đọc từ toán, biết viết các phép tính đến việc tận dụng vốn kiến thức toán đã học vào việc học toán và các môn học khác; Do vậy bộ sách hoàn toàn phù hợp cho việc dạy và học trong nhà trường.\r\n\r\nĐể đáp ứng kịp thời nhu cầu của giáo viên, học sinh trong tỉnh một cách đầy đủ bộ tài liệu sách giáo khoa toán song ngữ Việt – Anh phục vụ năm học 2014 – 2015, Các Sở Giáo dục và Đào tạo đã thông báo cho các đơn vị giáo dục biết và phổ biến đến giáo viên, học sinh đăng ký mua và đồng thời đặt mua để dùng vào thư viện trường học phục vụ cho việc giảng dạy.', 29400, 27500, 1, '2018-11-01 08:48:37', '2018-11-01 08:48:37'),
(11, 'Giải Sách Bài Tập Toán Lớp 9 - Tập 2', 'Trần Tiến Tự', 'Toán học', '1541062170_879737145.gif', 'Cuốn sách được biên soạn nhằm giúp các em học sinh có thêm tài liệu tham khảo để giải các bài tập Toán trong sách bài tập.\r\n\r\nCuốn sách được biên soạn một cách có hệ thống và rõ ràng, giúp các em học sinh dễ dàng nắm bắt các phương pháp giải cũng như kiến thức cơ bản để có thể giải các dạng bài tập trong sách, các kì kiểm tra định kì.\r\n\r\nHi vọng Giải Sách Bài Tập Toán Lớp 9 - Tập 2 sẽ là hành trang hữu ích của các em học sinh.', 45600, 42200, 1, '2018-11-01 08:49:30', '2018-11-01 08:49:30'),
(12, 'Hoa Tư Dẫn (Tái Bản Có Bổ Sung)', 'Đường Thất Công Tử', 'Tiểu thuyết', '1541062281_603988517.gif', 'Những ngày thành tan nước mất, công chúa Vệ Quốc là Diệp Trăn đã hi sinh thân mình vì nước, và nhờ viên giao châu nên chết đi sống lại.\r\n\r\nKhi nàng gảy lên điệu Hoa Tư, có thể dệt lên mộng cảnh, thỏa mãn khát khao trong đáy tim con người.\r\n\r\nTuy nhiên, khi viên giao châu bị đập vỡ, Diệp Trăn và Tô Dự - người nàng yêu thương cuối cùng cũng không vượt qua được vận mệnh như trò đùa…\r\nNàng sẽ dùng hết sức lực và số mạng để diễn tấu khúc ca cuối cùng, vì ai mà cất lên?\r\n\r\n02 tập “Hoa tư dẫn” vốn có trước đây, trong lần tái bản này sẽ được Quảng Văn in gộp lại thành 01 tập, khổ sách 16x24cm. Sách tái bản có bổ sung ngoại truyện mới, có kèm theo bookmark và poster dành tặng bạn đọc.\r\n\r\n* * *\r\n\r\nĐây là một câu chuyện diễn ra vào thời loạn thế. Những ngày thành tan nước mất, công chúa nước Vệ là Diệp Trăn đã hy sinh thân mình vì nước, nhờ viên giao châu của Quân sư phụ nên chết đi sống lại. Nhưng bây giờ nàng không có hơi thở, không có cảm giác, không có trái tim, trên mặt vẫn còn một vết sẹo không thể xóa mờ. Từ đó nàng đổi tên thành Quân Phất. Quân sư phụ nói rằng ông muốn nàng đi hành thích Trần hầu, kẻ thù của đất nước và vương tộc nàng. Viên giao châu trong lồng ngực Quân Phất phong ấn Hoa Tư dẫn – một loại thuật phép thượng cổ. Nếu ai đó uống vào dù chỉ là một giọt máu của nàng, Quân Phất có thể tìm ra điệu Hoa Tư (tên một điệu nhạc cổ) phù hợp nhất với người đó. Đánh điệu nhạc đó lên có thể tạo ra một mộng cảnh, mộng cảnh ấy là sự tái hiện của quá khứ. Muốn thoát ra khỏi mộng cảnh ấy phải xem người đó có thể thoát khỏi tâm mê của chính mình hay không. Quân sư phụ muốn Quân Phất giết Trần hầu theo cách đó.\r\n\r\n\"Hoa Tư dẫn\" là một câu chuyện vô cùng hấp dẫn, đặc sắc và độc đáo. Thực ra chủ đề chính của tác phẩm vẫn là về đề tài tình yêu đôi lứa nhưng lại được xây dựng cực kỳ sáng tạo. Mỗi một mối tình, mỗi cuộc đời của một nhân vật trong \"Hoa Tư dẫn\" đều mang một ý nghĩa, một thông điệp, một quan điểm riêng của tác giả về cuộc sống và tình yêu, để lại cho độc giả nhiều điều để suy ngẫm. Đường Thất Công Tử có một lối kể chuyện độc đáo, vừa cổ điển lại vừa hiện đại, hài hước. Bên cạnh những câu chữ mang đậm phong vị văn thơ cổ của một câu chuyện cổ trang, những lời bình luận và những đoạn đối thoại hài hước, đầy bất ngờ của các nhân vật lại mang đến cho người đọc cảm giác hiện đại rất rõ nét. Điều đó khiến cho những câu chuyện tình buồn trong cuốn truyện này được nhìn nhận dưới một góc nhìn khác hơn, không đơn thuần là bi kịch như nhiều truyện khác.', 97300, 85200, 1, '2018-11-01 08:51:21', '2018-11-01 08:51:21'),
(13, 'Thiên Sơn Mộ Tuyết', 'Phỉ Ngã Tư Tồn', 'Tiểu thuyết', '1541062351_849444343.gif', 'Đổng Tuyết là một cô gái mồ côi cả cha lẫn mẹ, sống cùng cậu mợ của mình. Cuộc sống “ở nhờ” đó đối với cô giống như địa ngục, hàng ngày nhìn đứa con của cậu mợ được bao bọc trong tình yêu thương của cha mẹ, cô không khỏi cảm thấy chạnh lòng. Tuổi ấu thơ vốn chẳng có niềm vui, nhưng may mắn thay, những năm tháng cấp ba, cô đã yêu được một chàng trai tốt.\r\n\r\nTiêu Sơn học cùng cô, hai người đã có quãng thời gian bên nhau thật đẹp, nhưng chỉ vì một sự hiểu lầm mà họ chia tay. Cô lên thành phố học đại học, nhưng số phận lại đưa đẩy cô vào tay một người đàn ông mà cô luôn coi là tên quỷ dữ. Mạc Thiệu Khiêm đã có vợ, cô luôn nghĩ cô sống với anh ta như một “gái bao”, không hơn không kém, chỉ mong một ngày anh ta chán cô và đá cô ra khỏi nhà. Nhưng chờ mãi, ngày ấy chẳng đến. Mọi chuyện vỡ lở, cô bị bạn bè khinh rẻ, đúng lúc ấy cô gặp lại Tiêu Sơn, họ muốn quay lại với nhau, nhưng cô luôn tự ti về thân phận của mình. Cả anh và cô đều có nỗi đau riêng, có những mối quan tâm riêng, họ chưa thể quay về với nhau. Nhưng cô không hề biết Mạc Thiệu Khiêm – cái người mà cô luôn coi là tên quỷ dữ ấy cũng có nỗi đau khổ riêng. Anh ta yêu cô, yêu cô hơn chính bản thân mình, anh ta chỉ ngủ với một mình cô, thậm chí anh ta còn chưa đụng tới người của cô vợ anh ta lấy một lần.\r\n\r\nSau đó, hàng loạt những bí mật, những dồn nén, những đau khổ được phơi bày. Đến cuối cùng, cô mới hiểu đươc “con quỷ dữ” ấy đã in sâu trong trái tim cô như thế nào. Và sau những nước mắt, họ có đến được với nhau?\r\n\r\nPhỉ Ngã Tư Tồn đã lấy tựa đề truyện là “Thiên sơn mộ tuyết” có ngụ ý lồng ghép tên các nhân vật có sự liên quan đến nhau. Ngụ ý của tác giả muốn nói đến mối quan hệ phức tạp và chiếm nhiều nước mắt của cả bốn nhân vật này, một quan hệ “vạn mối tơ vò”, thật mà giả, giả mà thật, yêu và hận đan xen chồng chất. Xuất xứ của câu “Thiên sơn mộ tuyết” là trích trong bài “Gò nhạn” của Nguyên Hiếu Vấn.\r\n\r\n“Hỏi thế gian, tình là vật gì\r\nMà khiến ta sống chết một lời hứa lụy\r\nLữ khách kẻ trời Nam người đất bắc\r\nKhi đôi cánh mỏi, nhớ những lúc ấm lạnh\r\nKhi hoan lạc vui vầy\r\nLúc chia ly đau khổ\r\nĐều chỉ vì si mê một người con gái\r\nLời người nói ra\r\nĐã xa tít trên tầng mây vạn dặm\r\nTuyết chiều trên nghìn ngọn núi\r\nBóng lẻ ấy biết về đâu”\r\n(Có nhiều cách dịch khác nhau cho câu thơ này: “Tuyết chiều in núi ẩn/Bóng lẻ bước phân vân.” – Ngô Hồ Anh Khôi dịch).', 81700, 70000, 1, '2018-11-01 08:52:31', '2018-11-01 08:52:31'),
(14, 'Anh Có Thích Nước Mỹ Không? (Tái Bản 2018)', 'Tân Di Ổ', 'Tiểu thuyết', '1541062426_945148477.gif', 'Trịnh Vy, 18 tuổi, có làn da trắng, đôi má hồng bầu bình tự nhận mình là Ngọc diện Tiểu Phi Long, một cô gái vô tư, cuộc sống dường như không có gì khiến cô phải buồn. Trịnh Vy quyết định thi vào Học viện Kiến trúc của thành phố G vì một lời hẹn ước với Lâm Tịnh - chàng trai sống cùng khu nhà tập thể với cô và hơn cô 5 tuổi.\r\n\r\nTừ khi còn rất nhỏ cô đã nói trước mặt mọi người là sẽ lấy Lâm Tịnh. 17 năm cô mải miết theo anh trên mọi con đường anh đi, đến cuối cùng cô tưởng như mình đã được ở gần anh sẽ không phải xa cách. Thật không ngờ, chuyện của người lớn - chuyện mẹ cô và cha anh đã từng yêu nhau đã khiến cho hai bên gia đình tan vỡ. Lâm Tịnh đã chọn con đường ra đi, sang Mĩ bỏ cô ở lại với bao câu hỏi ngổn ngang.\r\n\r\nThời gian vẫn trôi, con người vẫn phải sống, Trịnh Vy mạnh mẽ tiếp tục bước tiếp con đường mình phải đi. Cô làm thư ký cho Giám đốc Công ty 2 trực thuộc Tập đoàn Kiến trúc Trung Quốc, trước kia cô nộp hồ sơ vào đây vì Trần Hiếu Chính cũng nộp hồ sơ. Nhưng nay không còn anh cô vẫn đi làm vì cô thấy đây là cơ hội cô có thể phát triển sự nghiệp.\r\n\r\nDưới sự dìu dắt của Giám đốc Chu Cù, một Trịnh Vy sốc nổi, bốc đồng, bừa bãi đã trở thành thư ký Trịnh điềm đạm trong giao tiếp, cẩn trọng trong công việc. Cô Lý Chủ tịch Công đoàn của công ty đã giới thiệu cho cô rất nhiều chàng trai, cô nghĩ mình cũng nên tìm một người để nương tựa. Vậy là cô lao vào các cuộc hẹn hò, người thích cô thì cô không thích, mà người cô thích lại chẳng có tình cảm với cô, trước những chàng trai xa lạ cô luôn có một câu hỏi \"kinh điển\": \"Anh có thích nước Mỹ không?\"', 96000, 85000, 1, '2018-11-01 08:53:46', '2018-11-01 08:53:46'),
(15, 'Truyện Ngôn Tình - Giá Đâu Đó Có Người Đợi Tôi (Tái Bản 2016)', 'Anna Gavalda', 'Tiểu thuyết', '1541062516_2050032790.PNG', 'Mười hai truyện ngắn trong tập truyện ngắn đã phác hoạ rõ nét chân dung những con người tràn đầy hy vọng phù phiếm hay mang nỗi thất vọng nặng nề. Họ không phải là những người hùng, họ chỉ đơn thuần là con người. Họ không tìm cách thay đổi thế giới. Chúng ta vẫn gặp họ hàng ngày nhưng không hề chú ý đến họ, không hề để tâm đến gánh nặng tình cảm mà họ đang mang và bỗng nhiên tất cả được hiện diện dưới ngòi bút vô cùng tinh tế của Anna Gavalda. Thông qua hình ảnh những con người đó, Gavalda đã gián tiếp làm sáng tỏ cuộc sống của chính chúng ta…\r\n\r\n“Tôi gặp gỡ mọi người. Tôi quan sát họ. Tôi hỏi xem buổi sáng họ thức dậy lúc mấy giờ, họ làm nghề gì để sinh sống và chẳng hạn như họ thích ăn món gì tráng miệng. Tiếp theo đó, tôi nghĩ về họ. Tôi lại hình dung ra khuôn mặt, đôi bàn tay và thậm chí cả màu sắc đôi tất họ mang dưới chân. Tôi nghĩ đến họ suốt hang tiếng đồng hồ, thậm chí hàng năm trời, thế rồi một ngày kia, tôi thử viết về họ.”\r\n\r\n“Đó hầu như không là gì cả, đó thuộc về nghệ thuật vĩ đaị. Từ lối viết nhẹ nhàng, tuyệt vời và mỉa mai hài hứơc đến lạnh lung tới trái tim đau khổ đã tạo ra những cảm xúc thật khó phai và khiến ta xáo động. Anna Gavalda, cô ấy thật tuyệt vời.\"\r\n\r\n(Télérama)\r\n\r\n“Tất cả thật tuyệt vời, chất axít-ăn-mòn-làm-căng-thẳng-thần-kinh trong các tác phẩm của Anna Gavalda. Nhưng hãy thật cảnh giác, có thể đó là một cô gái phóng túng thất bại nhưng cũng có thể là một cô gái thành công…”\r\n\r\nDominique Durand (Canard Enchainé)\r\n\r\nTrích đoạn:\r\n\r\n“Người đàn ông và người đàn bà đó đang ngồi trong một chiếc xe sản xuất tại nước ngoài. Chiếc xe có giá ba trăm hai mươi nghìn quan và, lạ lùng thay, chính là cái giá ghi trên giấy chứng nhận thực đã trả thuế ôtô đã khiến người đàn ông do dự khi ở chỗ đại lý độc quyền.\r\n\r\nGic-lơ bên phải chạy kém. Chuyện ấy khiến ông ta phát điên.\r\n\r\nThứ hai, ông sẽ nhờ cô thư ký gọi cho salomon. Ông thoáng nghĩ tới bộ ngực của cô thư ký, nó lép kẹp. Ông chưa từng ngủ với các cô thư ký riêng. Làm thế thật tầm thường và ngày nay, làm thế còn khiến chúng ta rất mất nhiều tiền. Dẫu sao thì ông không còn phản bội vợ nữa, kể từ hôm ông và Antoine Say đùa nhau bằng cách lần lượt tính toán khoản nghĩa vụ cấp dưỡng của mỗi người khi đang chơi dở một ván golf.\r\n\r\nHọ đang cho xe chạy về căn nhà nghỉ cuối tuần ở nông thôn. Một trang trại hết sức xinh xắn ngay gần Angers. Những tỷ lệ tuyệt vời.\r\n\r\nHọ đã mua nó với giá rẻ mạt. Trái ngược với chi phí sửa sang sau đó…”', 59000, 55000, 1, '2018-11-01 08:55:16', '2018-11-01 08:55:16'),
(16, 'Truyện ngôn tình - Cô Gái Năm Ấy Chúng Ta Cùng Theo Đuổi (Tái Bản)', 'Cửu Bá Đao', 'Tiểu thuyết', '1541062596_1285216207.PNG', 'Tuổi thanh xuân ấy, phải chăng như một cơn mưa rào…\r\n\r\nNăm chàng trai Tạ Minh Hòa, Tạ Mạnh Học, Liêu Anh Hoằng, Trương Gia Huấn, Kha Cảnh Đằng, năm tính cách khác biệt nhưng mang “nhiệt huyết nam nhi tưng bừng” của mình yêu cùng một cô gái thanh tú, ngoan hiền và học giỏi nhất lớp, Thẩm Gia Nghi.\r\n\r\nTuổi thanh xuân ấy,\r\n\r\nKha Cảnh Đằng – “chuyên gia quậy phá đứng đầu bản danh sách đen” không bao giờ bị đánh bại bởi những hình phạt do thầy cô đưa ra nhưng lại cảm thấy tự ti xấu hổ khi đứng trước Thẩm Gia Nghi.\r\n\r\nTuổi thanh xuân ấy,\r\n\r\nChiếc áo học trò của Kha Cảnh Đằng đầy những dấu mực xanh do đầu bút của Thẩm Gia Nghi đâm vào…cho đến khi anh quay lại.\r\n\r\nMột lần để nói: “Kha Cảnh Đằng, tớ bảo này, hôm qua ngoài cửa nhà tớ có một con chó hoang, tên là Tiểu Bạch…”. Lần khác để hỏi: “Cậu làm gì mà ngủ say như chết vậy, hôm qua thức đêm hả?”\r\n\r\nNhững chấm mực xanh kia nhưng những chấm kỷ niệm, nhỏ thôi, từng chút một nhưng trên nền áo trắng tinh khôi, nó thật nổi bật, phải không?.  Tuổi thanh xuân của một đời người cũng vậy, thoáng đến rồi lại lặng lẽ qua đi nhanh chóng, nhưng những gì ở lại, thật làm ta không thể nào quên...', 76500, 72000, 1, '2018-11-01 08:56:36', '2018-11-01 08:56:36'),
(17, 'Thất Tịch Không Mưa', 'Lâu Vũ Tình', 'Tiểu thuyết', '1541062777_1758122621.gif', 'Thất tịch: Mùng 7 tháng 7 âm lịch, chính là lễ Valentine của Trung Quốc. Cô sinh ngày Mùng 7 tháng 7 - Ngày Thất tịch.\r\n\r\nTừ nhỏ cô đã thầm yêu anh, như số kiếp không thể thay đổi tình yêu trong sáng ấy, như lần đầu được nếm mùi vị của quả khế mới chín. Sau đó cô và anh xa nhau, gặp lại đều cách nhau ba năm. 15 tuổi, anh lên phía bắc học, từ đó mất liên lạc; 18 tuổi, cô nông nổi đi gặp anh, đổi lại là sự đau lòng; 21 tuổi, cuối cùng anh cũng quay về để chịu tang mẹ; 24 tuổi, anh kết hôn, đưa người vợ mới cưới tới tận nơi xa. Anh từng là thần hộ mệnh của cô, dịu dàng, cẩn thận che chở, bao dung. Đã từng ngoắc tay với cô, thề sẽ mãi mãi ở bên nhau. Cô có thể mất đi tất cả, nhưng không thể không có anh - người hiểu cô nhất. Ngày 7-7 là ngày gặp mặt của Ngưu Lang Chức Nữ, mưa ngày 7-7 là nước mắt của nỗi nhớ nhung vậy. Giờ cô 27 tuổi, liệu có thể có một ngày 7-7 không mưa, để cô được gặp lại anh một lần nữa...\r\n\r\nHai con người yêu nhau đến tận xương tủy, yêu đến vụn vỡ con tim nhưng lại không thể nào đến với nhau. Hai con người ấy mang theo con tim khiếm khuyết đi tìm kiếm yêu thương trong thế giới ngoài kia nhưng không thể. Vì với cô, anh là Thẩm Hàn Vũ độc nhất vô nhị không ai có thế thay thế, chỉ có một mình anh. Còn với anh, cô là Thẩm Thiên Tình mà anh yêu quí nhất, là người mà anh thề sẽ bảo vệ suốt đời, không có cô anh chỉ là một cái xác không hồn. Một tình yêu đẹp đến thế, sâu nặng đến thế, thế nhưng họ lại không thể là của nhau. Không thể trách anh, không thể trách cô, có chăng là oán hận cái số phận đã đặt tình yêu nồng đậm của họ vào một tình huống quá éo le, biến nó trở thành bi kịch của cả cuộc đời. Anh yêu cô, yêu đến đau lòng, nhưng chỉ có thể ở bên cô, chăm sóc cô với tư cách là một người anh trai, anh yêu cô, yêu đến mức thà để cô được thanh thản đã không ngần ngại mang một trái tim trống rỗng đi tìm kiếm hình bóng người con gái anh yêu trong những cô gái khác. Còn cô, cô yêu anh từ bé, yêu đến mức đối với cô, chỉ cần anh là đủ, chỉ cần anh tồn tại thì cô hạnh phúc, thế nhưng tình cảm ấy bị thứ bi kịch đau lòng kia ngăn chặn.\r\n\r\nCái chết - có nhiều người sẽ xem nó là một điều tồi tệ nhất, nhưng với cái chết trong câu chuyện này thì nó là cách giải thoát cho họ khỏi số phận đầy bi ai và đau đớn đến xé lòng kia. Và như anh đã nói: “Tình, đợi anh”, cô sẽ đợi, đợi anh thực sự đến bên cô, đợi để được thuộc về nhau trọn vẹn, đợi để chìm đắm trong tình yêu của họ, và đợi, đợi để thực sự được là một người con gái yêu anh.', 59200, 57000, 1, '2018-11-01 08:59:37', '2018-11-01 08:59:37'),
(18, 'Tam Sinh Tam Thế Chẩm Thượng Thư (Tập 2A + 2B) - Bìa Mềm', 'Đường Thất Công Tử', 'Tiểu thuyết', '1541062848_1290960187.gif', '“Tam sinh tam thế - Chẩm thượng thư” nằm trong hệ liệt “Tam sinh tam thế”, viết về Phượng Cửu (cháu gái Bạch Thiển) và Đông Hoa Đế Quân (hai nhân vật đã xuất hiện trong “Tam sinh tam thế - Thập lý đào hoa”). “Tam sinh tam thế - Chẩm thượng thư” là một câu chuyện vô cùng hấp dẫn, độc đáo và đặc sắc. Nếu như tập 1 của cuốn sách đem lại cho các bạn vô vàn nụ cười vì sự hài hước và có phần “quái gở” của Đông Hoa thì với tập 2, câu chuyện vẫn dí dỏm như thế, nhưng lại sâu lắng hơn, xúc động và day dứt hơn.\r\n\r\nDưới ngòi bút tài hoa của Đường Thất Công Tử, tâm lý nhân vật, những chuyển biến trong suy nghĩ, thái độ và cảm xúc của từng nhân vật hiện lên vô cùng sắc nét. Đoạn kết viên mãn và hạnh phúc của câu chuyện tình yêu “trái ý thiên mệnh” giữa Đông Hoa - Phượng Cửu trong tập 2 này chắc chắn sẽ để lại trong lòng bạn đọc nhiều ấn tượng.Chấp niệm suốt hai nghìn năm chỉ đổi lại hai chữ vô duyên.Nếu chung quy là vô duyên vậy tại sao lại cho chúng ta gặp nhau, chỉ một lần gặp gỡ mà vấn vương nghìn năm?Trong mộng cảnh trùng trùng mây mù có hình bóng của ai, hủy diệt nỗi tương tư của ai, chôn vùi đời này kiếp trước của ai?\r\n\r\n“Nàng muốn gì?”.“Mong muốn cả đời ta chỉ là được thấy hình bóng mình trong mắt chàng mà thôi”.\r\n\r\n“Chàng rất tốt, chỉ là ta và chàng không có duyên mà thôi”.“Thiên mệnh nói có duyên thì sao, vô duyên thì sao, bản quân chưa từng sợ hãi thiên mệnh, cũng không cần thiên mệnh bố thí”.\r\n\r\n“Tam sinh tam thế - Chẩm thượng thư” tập 2 nhận được rất nhiều yêu mến của độc giả: \r\n\r\n\"Dùng ba ngày để đọc hai tập sách Tam sinh tam thế Chẩm thượng thư, tôi có rất nhiều cảm xúc, muốn viết gì đó nhưng lại không biết viết gì, chỉ có thể nói rằng một lần nữa tôi lại bị Đường Thất Công Tử chinh phục. (Độc giả: villechansons)\r\n\r\nĐường Thất là một tác giả rất xuất sắc, văn của chị vừa hóm hỉnh khiến người ta bật cười rồi lại đau đớn đến mức làm người ta bật khóc ngay được. (Độc giả: Lala)\r\n\r\nTam sinh tam thế Chẩm thượng thư kết thúc nhanh quá, làm tôi gấp sách lại mà vẫn còn thấy ngơ ngác và tiếc nuối. (Độc giả: San Nam)', 110600, 105000, 1, '2018-11-01 09:00:48', '2018-11-01 09:00:48'),
(19, 'Yêu Đúng Lúc, Gặp Đúng Người', 'Cổ Tây Tước', 'Tiểu thuyết', '1541062902_125279320.gif', 'Một câu chuyện ấm áp đáng yêu khiến tất cả mọi người đều vui vẻ. Một câu chuyện đáng yêu khác tiếp nối sau “All in love” của Cố Tây Tước. Cuốn sách được biết đến với tên trân mạng “ĐÚNG NGƯỜI, ĐÚNG THỜI ĐIỂM”.\r\n\r\n“Đúng thời điểm, gặp đúng người, không phải là rung động mãnh liệt, mà là yên bình vĩnh cửu.”\r\n\r\nCó người nói, Giang An Lan lạnh lùng cao ngạo, vênh váo coi trời bằng vung; Có người nói, trêu trời chọc đất cũng tuyệt đối không được chọc vào Giang An Lan, bởi vì anh ta luôn có thể khiến bạn hối hận chỉ mong làm lại từ đầu; Có người nói, Giang An Lan, đến cả “mặt dày” cũng là đẳng cấp đại thần.\r\n\r\nTrong lòng Diêu Viễn, Giang An Lan cũng đã từng là một vật trưng bày có thể nhìn từ xa nhưng chẳng thể lại gần nghịch ngợm.\r\n\r\nMãi cho đến một ngày, anh ép mua ép bán, “meo” một tiếng với cô, cô liền cảm thấy cả thế giới này dường như đã thay đổi.\r\n\r\nAnh nói: “Chỉ cần em nhìn thấy anh rồi là sẽ chẳng thèm liếc mắt nhìn người khác nữa đâu.”\r\n\r\nAnh nói: “Cái chuyện ép người khác làm bạn gái mình, tôi chỉ làm với Nhược Vi Quân Cố thôi.”\r\n\r\nAnh nói: “Anh không biết theo đuổi người khác thế nào, nếu em muốn từ từ thôi thì anh cũng sẽ giảm tốc độ xuống.”\r\n\r\nAnh nói: “Tiểu Viễn… anh không lương thiện, nhưng anh tuyệt đối không phụ lòng em.”\r\n\r\nAnh yêu à, có cần câu nào câu nấy đều bắt chẹt người khác vậy không?\r\n\r\nThời khắc này, hoa tuyết nhẹ nhàng thả mình rơi xuống trên mái đầu đen mượt của anh, ánh mắt anh vương vấn ý cười mà cũng tràn đầy yêu thương chăm sóc: “Về sau anh là do em quản lý rồi.”\r\n\r\nNếu có thể chia ly thì đều không phải yêu nhất. Rời đi không được mới là số trời đã định.', 88500, 85000, 1, '2018-11-01 09:01:42', '2018-11-01 09:01:42'),
(20, 'Bên Nhau Trọn Đời - Bản 10 Năm', 'Cố Mạn', 'Tiểu thuyết', '1541062955_414589256.jpg', 'Vì một bí mật đau buồn trong quá khứ, Triệu Mặc Sênh và Hà Dĩ Thâm chia tay khi tình yêu giữa họ vừa chớm nở. Dù xa cách nhưng tình yêu của Dĩ Thâm vẫn luôn hướng về Mặc Sênh. Bảy năm sau, Hà Dĩ Thâm đã là một luật sư nổi tiếng, còn Triệu Mặc Sênh trở thành nhiếp ảnh gia. Sau cuộc hội ngộ tại siêu thị, hai người một lần nữa bước vào cuộc sống của nhau, nhưng nỗi đau từ lần chia tay trước đấy vẫn còn đó.\r\n\r\nCuối cùng, dù có chạy trốn như thế nào, muốn quên anh ra sao, số phận vẫn để Mặc Sênh về bên Dĩ Thâm. Một cuộc hôn nhân tưởng chừng hoang đường nhưng lại trói buộc hai con người ấy lại với nhau một lần nữa. Mọi hiểu lầm đều được hóa giải, hạnh phúc lại tràn ngập như ánh nắng mùa xuân.\r\n\r\nMột chuyện tình không quá đau thương, không quá phức tạp nhưng lại khiến người đọc mãi không thể quên. Bên nhau trọn đời đã trở lại với ấn bản kỷ niệm mười năm kể từ lần đầu phát hành tại Việt Nam cùng diện mạo mới. Nội dung sách đã được bổ sung một vài tình tiết chưa từng có trong phiên bản trước, đồng thời in kèm lời chúc cùng chữ ký của tác giả Cố Mạn và bộ 5 tranh màu minh họa của họa sĩ ENO Hà Hà Vũ.', 93750, 87000, 1, '2018-11-01 09:02:35', '2018-11-01 09:02:35'),
(21, 'Bữa Trưa Tình Yêu (Ấn Bản Kỷ Niệm) - Bổ Sung 5 Ngoại Truyện', 'Cố Mạn', 'Tiểu thuyết', '1541063007_537662633.gif', 'Bữa trưa tình yêu - Đây là tác phẩm kể về lịch sử đấu tranh của nhân viên quèn Sam Sam dưới tiếng nghiến răng kèn kẹt của Boss Phong Đằng. Càng chiến càng bại, càng bại càng chiến, cuối cùng Sam Sam đành phải ngoan ngoãn đầu hàng...\r\n\r\nĐại boss bá đạo và thỏ trắng ngây thơ\r\n\r\nĐại boss vừa kỳ cục, vừa kiêu gạo, thích bắt nạt, tính trẻ con... nhưng cũng vô cùng chu đáo dịu dàng...\r\n\r\nThỏ trắng thật thà, trong sáng, ngây thơ, đặc biệt là luôn bị khuất phục dưới tài sắc của Đại boss.\r\n\r\nTừ một lần hiến máu cho em gái Đại boss để rồi thỏ trắng ngây thơ lĩnh luôn hậu quả phải nhẫn nhục kiêm chức ôsin gắp rau, vì Đại boss đã nói rồi, không thể lãng phí thức ăn, nên những thứ Đại boss không ăn thì ôsin gắp rau phải ăn hết!\r\n\r\nThức ăn là chân lý, đấu với Đại boss là khờ khạo vô cùng, nịnh nọt xun xoe mới là đúng đắn!\r\n\r\nThỏ trắng không phải phượng hoàng hay thiên nga, nhưng lại khiến ánh mắt Đại boss luôn dõi theo, cũng tại bởi thỏ trắng “dễ ăn” mà thôi!', 81750, 78000, 1, '2018-11-01 09:03:27', '2018-11-01 09:03:27'),
(22, 'Kỹ Năng Sống Đầu Đời Của Bé (Tập 2)', 'Nhiều Tác Giả', 'Kỹ năng sống', '1541063120_270542582.gif', 'Từ lúc ấu thơ đến khi trưởng thành, có rất nhiều điều mà tất cả các bé sẽ phải học hỏi và trải qua: tính tự lập, biết yêu thương, biết chia sẻ, đoàn kết, giữ lời hứa, kiên trì,… Tuy nhiên, các bé vốn hiếu động và non nớt, bỡ ngỡ trước mọi thứ nên việc học những kỹ năng này vốn chẳng dễ dàng gì.\r\n\r\nBộ sách Kỹ năng sống đầu đời của bé chính là kim chỉ nam cho các bậc cha mẹ trong việc dạy dỗ và uốn nắn con em mình. Mỗi câu chuyện sẽ gồm nhiều tình huống thú vị, gần gũi với trẻ em, qua đó dần trang bị những kỹ năng sống đầu đời hữu ích đến các bé yêu.', 35000, 32000, 1, '2018-11-01 09:05:20', '2018-11-01 09:05:20'),
(23, 'Trẻ Rèn Kỹ Năng Sống: Khi Áo Bị Bung Nút', 'Nhiều Tác Giả', 'Kỹ năng sống', '1541063174_570864549.gif', 'Bất ngờ cúp điện. Bất ngờ trượt té. Bất ngờ bị đứt nút áo. Bất ngờ lạc người thân… Dù ở nhà, ở trường, nơi vắng vẻ hay đông đúc, chỗ nào cũng có thể xảy đến những tình huống bất ngờ với bé. Bé có thể òa khóc vì sợ hãi hoặc tự chọn một giải pháp sai lầm.Bộ sách TRẺ RÈN KỸ NĂNG SỐNG không chỉ kể với độc giả nhỏ những kinh nghiệm, phương pháp hữu ích mà còn có các bài luyện tập thiết thực, giúp bé giữ được bình tĩnh và an toàn khi đối mặt với các sự cố.', 8300, 7500, 1, '2018-11-01 09:06:14', '2018-11-01 09:06:14'),
(24, 'Kỹ Năng Sống Cùng Poki (8+) - Tập 1', 'Nhiều Tác Giả', 'Kỹ năng sống', '1541063228_581109696.gif', 'Giáo dục kỹ năng sống cho học sinh đang là hoạt động thu hút sự quan tâm không chỉ của cha mẹ học sinh, giáo viên mà còn của cả toàn xã hội. Bởi lẽ kỹ năng sống có ý nghĩa và tác dụng to lớn đối với sự tồn tại và phát triển của con người trong bối cảnh xã hội hiện đại. Kỹ năng sống đang thực sự là  một trong những trụ cột quan trọng của công dân toàn cầu thế kỷ 21.\r\n\r\nVới chức năng nghiên cứu, ứng dụng, tư vấn phổ biến các vấn đề và thành tựu của khoa học giáo dục, Hội Khoa học tâm lý – Giáo dục Việt Nam hoan nghênh và ủng hộ Tổ chức Giáo dục và Đào tạo POKI Tân Á Châu biên soạn bộ sách Kỹ Năng Sống Cùng Poki dành cho học sinh tiểu học. Trong quá trình biên soạn, Hội đã cử các chuyên gia tâm lý, giáo dục, các cố vấn chuyên môn tham gia phản biện, góp ý cho nhóm tác giả hoàn thiện bộ sách này.\r\n\r\nĐây là bộ sách được trình bày công phu, với nội dung được chọn lọc cẩn thận, phù hợp với đặc điểm lứa tuổi, gần gũi với cuộc sống thường nhật. Nhóm tác giả đã sử dụng tối đa phương tiện trực quan để các em học tập, tiếp thu một cách dễ dàng và hiệu quả nhất. Bên cạnh đó, trong từng tập sách, nhân vật Poki và những người bạn được sử dụng để đồng hành với các em trong hành trình khám phá, hoàn thiện các kỹ năng, chuẩn bị một hành trang chu đáo để các em hứng thú, tự tin hội nhập và phát triển trong môi trường mới.\r\n\r\n“Đọc, xem và thực hành. Tất cả đều có trong một cuốn sách nhỏ.” – GS. TS. Lê Huy Bắc\r\n\r\n“Một bộ sách hội tụ đầy đủ và toàn diện các kỹ năng sống phù hợp với từng lứa tuổi để học sinh có được những năng lực cần thiết của công dân toàn cầu.” – TS Phạm Thanh Bình', 52500, 50000, 1, '2018-11-01 09:07:08', '2018-11-01 09:07:08'),
(25, 'Kỹ Năng Sống Cùng Poki (7+) - Tập 1', 'Nhiều Tác Giả', 'Kỹ năng sống', '1541063317_1771659955.gif', 'Giáo dục kỹ năng sống cho học sinh đang là hoạt động thu hút sự quan tâm không chỉ của cha mẹ học sinh, giáo viên mà còn của cả toàn xã hội. Bởi lẽ kỹ năng sống có ý nghĩa và tác dụng to lớn đối với sự tồn tại và phát triển của con người trong bối cảnh xã hội hiện đại. Kỹ năng sống đang thực sự là  một trong những trụ cột quan trọng của công dân toàn cầu thế kỷ 21.\r\n\r\nVới chức năng nghiên cứu, ứng dụng, tư vấn phổ biến các vấn đề và thành tựu của khoa học giáo dục, Hội Khoa học tâm lý – Giáo dục Việt Nam hoan nghênh và ủng hộ Tổ chức Giáo dục và Đào tạo POKI Tân Á Châu biên soạn bộ sách \"Kỹ năng sống cùng POKI\" dành cho học sinh tiểu học. Trong quá trình biên soạn, Hội đã cử các chuyên gia tâm lý, giáo dục, các cố vấn chuyên môn tham gia phản biện, góp ý cho nhóm tác giả hoàn thiện bộ sách này.\r\n\r\nĐây là bộ sách được trình bày công phu, với nội dung được chọn lọc cẩn thận, phù hợp với đặc điểm lứa tuổi, gần gũi với cuộc sống thường nhật. Nhóm tác giả đã sử dụng tối đa phương tiện trực quan để các em học tập, tiếp thu một cách dễ dàng và hiệu quả nhất. Bên cạnh đó, trong từng tập sách, nhân vật Poki và những người bạn được sử dụng để đồng hành với các em trong hành trình khám phá, hoàn thiện các kỹ năng, chuẩn bị một hành trang chu đáo để các em hứng thú, tự tin hội nhập và phát triển trong môi trường mới.\r\n\r\n\"Đọc, xem và thực hành. Tất cả đều có trong một cuốn sách nhỏ.\" – GS. TS. Lê Huy Bắc\r\n\r\n\"Một bộ sách hội tụ đầy đủ và toàn diện các kỹ năng sống phù hợp với từng lứa tuổi để học sinh có được những năng lực cần thiết của công dân toàn cầu.\" – TS Phạm Thanh Bình', 56000, 54000, 1, '2018-11-01 09:08:37', '2018-11-01 09:08:37'),
(26, 'Kỹ Năng Sống Dành Cho Học Sinh - Học Cách Cho Và Nhận', 'Ngọc Linh', 'Kỹ năng sống', '1541063368_1344298187.gif', 'Trí tuệ giống như ngọn đèn xuyên qua đêm tối, soi sáng con đường chông gai phía trước. Trí tuệ giống như chiếc chìa khóa diệu kỳ gợi mở cánh cửa tâm hồn. Trí tuệ giống như những tia nắng mặt trời ấm áp xua tan bóng tối lạnh giá phủ mờ nhân loại. Đấng tạo hóa có trí tuệ mới có thể tạo ra một thế giới diệu kì; nhân loại có trí tuệ chỉ đường sẽ bước sang thế giới hiện đại văn minh. Khi bạn có trí tuệ, bạn sẽ dễ dàng gặt hái được nhiều thành công trong cuộc sống. Bảy trăm năm trước, Giovanni Boccaccio đã nói: “Trí tuệ là cội nguồn hạnh phúc của con người”. Thật vậy, có trí tuệ, bạn sẽ được trải nghiệm niềm vui và mang lại hạnh phúc cho những người xung quanh.\r\n\r\nKhi mệt mỏi, hãy nhớ đến lời răn dạy của các bậc trí giả. Khi rơi vào đường cùng bế tắc, hãy lắng nghe tiếng lòng của người thông minh. Tôi tin rằng trên con đường đi tới thành công của chúng ta không chỉ có cầu vồng lấp lánh mà có cả mưa gió cản lối nhưng có trí tuệ giúp sức, cuối cùng bạn sẽ vượt qua gió mưa và đến được với ánh sáng mặt trời ấm áp.\r\n\r\nChúng tôi đã chọn lựa và tập hợp những câu chuyện nhiều màu sắc, đầy tính trí tuệ, hàm súc và giàu triết lí có tác dụng khích lệ ý chí thành bộ sách “Kỹ năng sống dành cho học sinh” bao gồm bảy cuốn: “Lòng biết ơn”, “Biết chấp nhận”, “Sự kiên cường”, “Học cách sống” , “Biết lựa chọn” , “Học cách cho và nhận”, “Biết trân trọng”. Có thể con đường phía trước của bạn còn nhiều trắc trở, hoặc bị chìm trong bóng tối lạnh giá, nhưng chúng tôi mong rằng bạn có thể hiểu được ý nghĩa sâu sắc từ các câu chuyện này, qua đó có được những suy ngẫm mới mẻ và sâu sắc hơn về ý nghĩa của cuộc sống.\r\n\r\nMong rằng trí tuệ sẽ trở thành người bạn đồng hành mãi mãi của bạn trên mọi hành trình để mang lại cho cuộc sống của bạn những khúc nhạc du dương ngọt ngào và những ánh hào quang lấp lánh!', 31200, 28000, 1, '2018-11-01 09:09:28', '2018-11-01 09:09:28'),
(27, 'Cambridge Young Learner English Test Movers 3: Student Book', 'Cambridge', 'Ngoại ngữ', '1541063538_1495229999.PNG', 'These practice tests from Cambridge ESOL are designed to evaluate the English level of primary learners aged 7-12. Updated to reflect the 2007 changes, they provide the first step towards the Cambridge ESOL main suite exams (e.g. KET, PET and FCE). There are 3 sets of tests for each of the 3 levels: Cambridge Starters, Cambridge Movers and Cambridge Flyers. Each set contains 3 full-colour tests, an audio cassette/CD, and an answer booklet. This is the second edition of Cambridge Young Learners English Tests 1 and is suitable for use with the new 2007 syllabus.', 118000, 115000, 1, '2018-11-01 09:12:18', '2018-11-01 09:12:18'),
(28, 'Oxford Bookworms Library (3 Ed.) 3: Australia and New Zealand Factfile', 'Christine Lindop', 'Ngoại ngữ', '1541063602_626023260.PNG', 'What do you find in these two countries at the end of the world? One is an enormous island, where only twenty million people live - and the other is two long, narrow islands, with ten sheep for every person. One country has the biggest rock in all the world, and a town where everybody lives under the ground; the other has a beach where you can sit beside the sea in a pool of hot water, and lakes that are bright yellow, green, and blue. Open this book and start your journey - to two countries where something beautiful or surprising waits around every corner.', 66000, 60000, 1, '2018-11-01 09:13:22', '2018-11-01 09:13:22'),
(29, 'Oxford Bookworms Library (3 Ed.) 1: Titanic Factfile', 'Tim Vicary', 'Ngoại ngữ', '1541063699_1530118069.gif', 'On a quiet sea, the biggest ship in the world is waiting. There is no noise from the engines. Up in the night sky there are hundreds of stars. Behind the ship, an iceburg - a great mountain of ice - goes slowly away into the black night. In the beautiful first-class rooms, rich passengers eat and listen to music. Down in the third-class cabins, families sleep. An exciting new life is waiting for them in America. But for many of the people in this small \'city on the sea\', this is their last night alive..', 58000, 56000, 1, '2018-11-01 09:14:59', '2018-11-01 09:14:59'),
(30, 'Oxford Bookworms Library (3 Ed.) 3: The USA Factfile', 'Alison Baxter', 'Ngoại ngữ', '1541063744_481760872.gif', 'Everybody knows about the United States of America. You can see its films, hear its music, and eat its food just about everywhere. Cowboys, jazz, hamburgers, the Stars and Stripes - that\'s the United States. But it\'s a country with many stories to tell. Stories of busy cities, beautiful forests and parks. Stories of a country that fought against Britain, and then against itself, to make the United States of today. Stories of rich and poor, black and white, Native American and immigrant. And the story of what it is like to be an American today...', 63000, 59000, 1, '2018-11-01 09:15:44', '2018-11-01 09:15:44'),
(31, 'Starter Toeic Third Edition', 'Compass', 'Ngoại ngữ', '1541063791_1498296625.gif', 'Starter Toeic Third Edition dành cho cho người Stater TOEIC luyện thi Toeic ở trình độ sơ cấp.\r\n\r\nCuốn sách là tài liệu luyện thi toeic được giới thiệu bởi khá nhiều giáoTài liệu luyện thi TOEIC này hỗ trợ bạn thông qua những bài tập thực hành nhấn vào trọng tâm; cùng lúc cung cấp những kiến thức nền tảng và những mẹo giúp bạn học tốt, xây dựng được những kỹ năng cần thiết, làm quen dần với hình thức thi TOEIC  viên ở các trung tâm anh ngữ với các trình độ sơ cấp và trung cấp.', 84000, 80000, 1, '2018-11-01 09:16:31', '2018-11-01 09:16:31'),
(32, 'Cambridge Primary Science 3: Learner Book', 'Paperback', 'Ngoại ngữ', '1541063908_72558696.PNG', 'Cambridge Primary Science is a flexible, engaging course written specifically for the Cambridge Primary Science curriculum framework\r\n\r\nThis Learner\'s Book for Stage 3 covers all objectives required by the curriculum framework in an engaging, visually stimulating manner. Learning through enquiry is supported by hands-on activity suggestions, which provide integrated coverage of the Scientific Enquiry objectives. Assessment is achieved through \'Check your progress\' questions at the end of each unit.', 229000, 200000, 1, '2018-11-01 09:18:28', '2018-11-01 09:18:28'),
(33, 'Cambridge Primary Science Challenge 1: Activity Book', 'Paperback', 'Ngoại ngữ', '1541063953_52967110.PNG', 'The Challenge and Skills Builders are differentiated activity books to be used alongside the Cambridge Primary Science course. Cambridge Primary Science is a flexible and engaging course written specifically for the Cambridge Primary Science Curriculum Stages 1 to 6. The course uses an enquiry-led approach focussed on making pupils think and work scientifically. The Challenge Activity Books provide extension activities for children who need more challenging activities to stretch their skills beyond the standard for success expected in Primary school. They include a full range of carefully levelled activities which help stretch and deepen a child\'s understanding, plus helpful guidance for explaining to the learner, teacher or parent the key scientific methods and concepts underpinning each exercise.', 130000, 120000, 1, '2018-11-01 09:19:13', '2018-11-01 09:19:13'),
(34, 'Cambridge Primary Mathematics 5: Learner Book', 'Paperback', 'Toán học', '1541063999_1992335653.PNG', 'This series is endorsed by Cambridge International Examinations and is part of Cambridge Maths.\r\n\r\nChildren will enjoy learning mathematics with this fun and attractive learner\'s book for stage 1. A variety of questions, activities, investigations and games that are designed to reinforce the concepts learnt in the core activities in the teacher’s guide and address misconceptions are included along with hints and tips. Clear, often pictorial, explanation of mathematical vocabulary will help children learn new terms whether they are native English speakers or second language speakers and great care has been made to ensure language is accessible.', 342000, 320000, 1, '2018-11-01 09:19:59', '2018-11-01 09:19:59'),
(35, 'Cambridge Primary Science 1:Activity Book', 'Paperback', 'Ngoại ngữ', '1541064050_901277420.PNG', 'Cambridge Primary Science is a flexible, engaging course written specifically for the Cambridge Primary Science curriculum framework. This Activity Book for Stage 1 contains exercises to support each topic in the Learner\'s Book, which may be completed in class or set as homework. Exercises are designed to consolidate understanding, develop application of knowledge in new situations, and develop Scientific Enquiry and literacy skills.\r\n\r\nThis Activity Book for Stage 1 contains exercises to support each topic in the Learner\'s Book, which may be completed in class or set as homework. Exercises are designed to consolidate understanding, develop application of knowledge in new situations, and develop Scientific Enquiry and literacy skills.', 72000, 65000, 1, '2018-11-01 09:20:50', '2018-11-01 09:20:50'),
(36, 'Cambridge Primary Science Skills Builder 1: Activity Book', 'Paperback', 'Ngoại ngữ', '1541064144_1090667238.PNG', 'The Challenge and Skills Builders are differentiated activity books to be used alongside the Cambridge Primary Science course.\r\n\r\nThe Challenge and Skills Builders are differentiated activity books to be used alongside the Cambridge Primary Science course. Cambridge Primary Science is a flexible and engaging course written specifically for the Cambridge Primary Science Curriculum Stages 1 to 6. The course uses an enquiry-led approach that helps pupils to think and work scientifically. Skills Builders provide consolidation activities for children who need extra learning opportunities to meet the standard for success. They also focus on scientific literacy for ESL children who find this a barrier to learning. A full range of activities help raise a child\'s scientific literacy and understanding to match their peers, with teacher/parental guidance on key scientific methods and concepts before each exercise.', 130000, 100000, 1, '2018-11-01 09:22:24', '2018-11-01 09:22:24'),
(37, 'Chiếp Chiếp Happy Birthday - Ehon Kỹ Năng Sống', 'Noriko', 'Kỹ năng sống', '1541064250_1528364419.gif', 'Nào cùng đi mua bánh sinh nhật,\r\n\r\nchiếp chiếp.\r\n\r\nChúng mình có được tự chọn quà,\r\n\r\nchiếp chiếp?\r\n\r\nCùng học cách đón mừng sinh nhật ấm áp\r\n\r\nvới nhà Chiếp chiếp!', 32000, 28000, 1, '2018-11-01 09:24:10', '2018-11-01 09:24:10'),
(38, 'Trẻ Rèn Kỹ Năng Sống - Cẩn Thận Với Nước', 'Thanh Xuân - Nghi Nghi', 'Kỹ năng sống', '1541064295_370900587.gif', 'Khi sàn nhà đang ướt, khi gặp vũng nước trên đường, khi đi chơi ở biển hay vùng sông nước,… bé cần làm gì để không bị trượt té vào đó?\r\n\r\n- Một tình huống dễ gặp\r\n\r\n- Một bài học kinh nghiệm\r\n\r\n- Vài luyện tập để trẻ được an toàn khi tiếp xúc với nước.\r\n\r\nBộ sách Trẻ rèn kỹ năng sống dành cho các bé từ 3 đến 8 tuổi. Sách kèm theo tranh vẽ màu, minh họa sinh động , ngộ nghĩnh.', 8300, 6500, 1, '2018-11-01 09:24:55', '2018-11-01 09:24:55'),
(39, 'Chiếp Chiếp Đến Chơi Nhà Bà - Ehon Kỹ Năng Sống', 'Noriko', 'Kỹ năng sống', '1541064336_975067968.gif', 'Hôm nay bố mẹ đi vắng,\r\n\r\nchiếp chiếp.\r\n\r\nChúng mình đến tá túc nhà bà,\r\n\r\nchiếp chiếp!\r\n\r\nChúng mình sẽ làm gì nhỉ,\r\n\r\nchiếp chiếp, học cách cư xử với ông bà.', 33000, 30000, 1, '2018-11-01 09:25:36', '2018-11-01 09:25:36'),
(40, 'Em Làm Việc Nhà - Ehon Kỹ Năng Sống', 'Tatsumi Nagisa - Nguyễn Đình Trực dịch', 'Kỹ năng sống', '1541064393_682954538.PNG', 'Việc nhà gồm có lau chùi, giặt giũ, dọn dẹp và rất nhiều công việc khác hàng ngày. Cuốn sách này giới thiệu đầy đủ,  các việc nhà và cách thức làm từng việc bằng lời hướng dẫn đơn giản và hình minh họa sinh động, để các bạn nhỏ từ mẫu giáo lớn đến cuối tiểu học đều thực hiện được.\r\n\r\nCùng làm việc nhà cũng là cơ hội tuyệt vời để con cái duy trì giao tiếp cùng bố mẹ. Cả gia đình hãy cùng nhau làm việc nhà trong tiếng cười đùa hạnh phúc nhé!', 66000, 62000, 1, '2018-11-01 09:26:33', '2018-11-01 09:26:33'),
(41, '168 Câu Chuyện Kỹ Năng Sống Cho Học Sinh- Vươn Lên Để Thành Công - Biến Điều Không Thể Thành Có Thể', 'Ngọc Linh', 'Kỹ năng sống', '1541064471_1478228403.gif', '\"Mỗi lần, khi chủ cửa hàng nói \"không\", Ginard lại giả vờ không nghe thấy, anh tiếp tục đến. Ngày cuối cùng tháng đó, chủ cửa hàng đã nói với chàng thanh niên Ginard có nỗ lực phi thường rằng \"Ta cũng phải thừa nhận rằng, ta cũng đang đi học và cậu chính là thầy giáo của ta. Để bày tỏ sự cảm kích, ta đồng ý ký kết hợp đồng quảng cáo, đó chính là học phí mà ta phải trả cho cậu.\"', 27300, 25000, 1, '2018-11-01 09:27:51', '2018-11-01 09:27:51');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `books`
--
ALTER TABLE `books`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
